In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt

x = [5, 9, 2, 3, 4, 6, 7, 0, 8, 12, 2, 9]

print(x[1])

print(x[1:4])

print([x[i] for i in [1,2,5]])

print([x[i] for i in range(0,5)] + [x[i] for i in range(9,12)])

print([x[i] for i in range(len(x)) if i not in range(10,12)])

9
[9, 2, 3]
[9, 2, 6]
[5, 9, 2, 3, 4, 12, 2, 9]
[5, 9, 2, 3, 4, 6, 7, 0, 8, 12]


In [ ]:
#2. Milk Sales - Statistical analysis
y = [33,44,29,16,25,45,33,19,54,22,21,49,11,24,56]

data = np.array(y).reshape(5,3)

df = pd.DataFrame(data, columns=["Shop1", "Shop2","Shop3"], index=["Mon", "Tue","Wed", "Thu", "Fri"])

print(df)

print("\n Statistical Summary for Each Day \n")
print(df.apply(lambda r: r.describe(), axis=0))

print("\n Statistical Summary for Each Shop \n")
print(df.apply(lambda r: r.describe(), axis=1))

     Shop1  Shop2  Shop3
Mon     33     44     29
Tue     16     25     45
Wed     33     19     54
Thu     22     21     49
Fri     11     24     56

 Statistical Summary for Each Day 

           Shop1      Shop2      Shop3
count   5.000000   5.000000   5.000000
mean   23.000000  26.600000  46.600000
std     9.924717  10.014989  10.737784
min    11.000000  19.000000  29.000000
25%    16.000000  21.000000  45.000000
50%    22.000000  24.000000  49.000000
75%    33.000000  25.000000  54.000000
max    33.000000  44.000000  56.000000

 Statistical Summary for Each Shop 

     count       mean        std   min   25%   50%   75%   max
Mon    3.0  35.333333   7.767453  29.0  31.0  33.0  38.5  44.0
Tue    3.0  28.666667  14.843629  16.0  20.5  25.0  35.0  45.0
Wed    3.0  35.333333  17.616280  19.0  26.0  33.0  43.5  54.0
Thu    3.0  30.666667  15.885003  21.0  21.5  22.0  35.5  49.0
Fri    3.0  30.333333  23.158872  11.0  17.5  24.0  40.0  56.0


In [13]:
# 3. Matrix Operations
x = np.array([[3,2], [-1,1]])
y = np.array([[1,4,0], [0,1,-1]])

print(" 2* x \n", 2* x)
print("\n x* x \n", x* x)
print("\n x %*% x \n", x @ x)
print("\n x%*% y \n", x @ y)
print("\n Tanspose \n", y.T)
print("\n Inverser \n", np.linalg.inv(x))



 2* x 
 [[ 6  4]
 [-2  2]]

 x* x 
 [[9 4]
 [1 1]]

 x %*% x 
 [[ 7  8]
 [-4 -1]]

 x%*% y 
 [[ 3 14 -2]
 [-1 -3 -1]]

 Tanspose 
 [[ 1  0]
 [ 4  1]
 [ 0 -1]]

 Inverser 
 [[ 0.2 -0.4]
 [ 0.2  0.6]]


In [15]:
# 4. Subscript Operations

x = np.array([[3,2], [-1,1]])
y = np.array([[1,4,0], [0,1,-1]])

print("\n a) x[1,] --> Print First Row \n", x[0,:] )
print("\n b) x[2,] --> Print Second Row \n", x[1,:] )
print("\n c) x[,2] --> Print Second Column \n", x[:,1] )
print("\n d) y[1,2] --> Element at row1 col2 \n", y[0,1] )
print("\n e) y[,2:3] --> Print Column 2 to 3 \n", y[:, 1:3] )


 a) x[1,] --> Print First Row 
 [3 2]

 b) x[2,] --> Print Second Row 
 [-1  1]

 c) x[,2] --> Print Second Column 
 [2 1]

 d) y[1,2] --> Element at row1 col2 
 4

 e) y[,2:3] --> Print Column 2 to 3 
 [[ 4  0]
 [ 1 -1]]
