In [17]:
import numpy as np
X = np.array([[64,71,53,67,55,58,77,57,56,51,76,68], [57,59,49,62,51,50,55,48,42,42,61,57],], dtype=float)

print("Original Data: \n", X)


Original Data: 
 [[64. 71. 53. 67. 55. 58. 77. 57. 56. 51. 76. 68.]
 [57. 59. 49. 62. 51. 50. 55. 48. 42. 42. 61. 57.]]


In [18]:
X_meaned = X-np.mean(X, axis=0)
print("\n Mean Centered Data:\n", X_meaned)


 Mean Centered Data:
 [[  3.5   6.    2.    2.5   2.    4.   11.    4.5   7.    4.5   7.5   5.5]
 [ -3.5  -6.   -2.   -2.5  -2.   -4.  -11.   -4.5  -7.   -4.5  -7.5  -5.5]]


In [19]:
cov_matrix = np.cov(X_meaned.T)
print("\nCovariance Matrix: \n", cov_matrix)


Covariance Matrix: 
 [[ 24.5  42.   14.   17.5  14.   28.   77.   31.5  49.   31.5  52.5  38.5]
 [ 42.   72.   24.   30.   24.   48.  132.   54.   84.   54.   90.   66. ]
 [ 14.   24.    8.   10.    8.   16.   44.   18.   28.   18.   30.   22. ]
 [ 17.5  30.   10.   12.5  10.   20.   55.   22.5  35.   22.5  37.5  27.5]
 [ 14.   24.    8.   10.    8.   16.   44.   18.   28.   18.   30.   22. ]
 [ 28.   48.   16.   20.   16.   32.   88.   36.   56.   36.   60.   44. ]
 [ 77.  132.   44.   55.   44.   88.  242.   99.  154.   99.  165.  121. ]
 [ 31.5  54.   18.   22.5  18.   36.   99.   40.5  63.   40.5  67.5  49.5]
 [ 49.   84.   28.   35.   28.   56.  154.   63.   98.   63.  105.   77. ]
 [ 31.5  54.   18.   22.5  18.   36.   99.   40.5  63.   40.5  67.5  49.5]
 [ 52.5  90.   30.   37.5  30.   60.  165.   67.5 105.   67.5 112.5  82.5]
 [ 38.5  66.   22.   27.5  22.   44.  121.   49.5  77.   49.5  82.5  60.5]]


In [20]:
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)
print("\n Eigen Values:\n", eigenvalues)
print("\n Eigen Vectors: \n", eigenvectors)


 Eigen Values:
 [ 0.00000000e+00+0.00000000e+00j  7.51000000e+02+0.00000000e+00j
 -7.01452805e-15+0.00000000e+00j  2.90052581e-15+5.15745696e-15j
  2.90052581e-15-5.15745696e-15j  4.75153016e-15+0.00000000e+00j
 -1.77200694e-15+0.00000000e+00j -4.23061216e-30+0.00000000e+00j
  5.19080198e-31+8.42853115e-32j  5.19080198e-31-8.42853115e-32j
 -7.19688055e-33+0.00000000e+00j  5.34289446e-33+0.00000000e+00j]

 Eigen Vectors: 
 [[-0.98355317+0.00000000e+00j -0.18061885+0.00000000e+00j
   0.00486858+0.00000000e+00j -0.11040389+6.25754932e-02j
  -0.11040389-6.25754932e-02j -0.15088144+0.00000000e+00j
   0.14514588+0.00000000e+00j  0.04617147+0.00000000e+00j
  -0.25094962-2.12017022e-01j -0.25094962+2.12017022e-01j
   0.98103497+0.00000000e+00j  0.98103642+0.00000000e+00j]
 [ 0.05686061+0.00000000e+00j -0.30963231+0.00000000e+00j
   0.15688175+0.00000000e+00j  0.11376682-1.30681147e-01j
   0.11376682+1.30681147e-01j  0.06179851+0.00000000e+00j
  -0.00470719+0.00000000e+00j  0.05949568+0.000000

In [21]:
k = 2
eigenvectors_k = eigenvectors[:,:k]
print(f"\n Top {k} Eigenvectors:\n", eigenvectors_k)



 Top 2 Eigenvectors:
 [[-0.98355317+0.j -0.18061885+0.j]
 [ 0.05686061+0.j -0.30963231+0.j]
 [ 0.01895354+0.j -0.10321077+0.j]
 [ 0.02369192+0.j -0.12901346+0.j]
 [ 0.01895354+0.j -0.10321077+0.j]
 [ 0.03790707+0.j -0.20642154+0.j]
 [ 0.10424445+0.j -0.56765924+0.j]
 [ 0.04264546+0.j -0.23222424+0.j]
 [ 0.06633738+0.j -0.3612377 +0.j]
 [ 0.04264546+0.j -0.23222424+0.j]
 [ 0.07107576+0.j -0.38704039+0.j]
 [ 0.05212223+0.j -0.28382962+0.j]]


In [22]:
X_reduced = X_meaned @ eigenvectors_k
print(f"\nPCA Reduced Data(k = {k}): \n", X_reduced)


PCA Reduced Data(k = 2): 
 [[ 2.67147415e-16+0.j -1.93778224e+01+0.j]
 [-2.67147415e-16+0.j  1.93778224e+01+0.j]]
