In [1]:
import numpy as np

A = np.array([
    [3, 1],
    [1, 3]
])

U, S, Vt = np.linalg.svd(A)

print("U Matrix:\n", U)
print("Singular Values:", S)
print("V Transpose:\n", Vt)

# Reconstruction:
A_reconstructed = U @ np.diag(S) @ Vt
print("Reconstructed Matrix:\n", A_reconstructed)


U Matrix:
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
Singular Values: [4. 2.]
V Transpose:
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
Reconstructed Matrix:
 [[3. 1.]
 [1. 3.]]


In [2]:
import numpy as np

A = np.array([
    [3, 1],
    [1, 3]
])

# Step 1: Compute A.T * A
ATA = A.T @ A

# Step 2: Eigen decomposition of ATA
eig_vals, eig_vecs = np.linalg.eigh(ATA)

# Step 3: Singular values = sqrt(eigenvalues)
singular_values = np.sqrt(eig_vals)[::-1]

# Step 4: V = eigenvectors of ATA
V = eig_vecs[:, ::-1]

# Step 5: U = A * V / singular_value
U = A @ V / singular_values

print("U:\n", U)
print("Singular Values:", singular_values)
print("V:\n", V)


U:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
Singular Values: [4. 2.]
V:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
